### ISSUE TITLE
DOCKER_TLS_VERIFY=1 will fail always the TLS check

### ISSUE THREAD

**Issue by mmannerm** [gesellix-docker/docker-client#12]
In de.gesellix.docker.client.protocolhandler.DockerURLHandler:
```
 if ((dockerTlsVerify && Boolean.valueOf(dockerTlsVerify) == FALSE) || "0".equals(dockerTlsVerify)) {
```
will always produce true and thus fail the check for TLS, because `Boolean.valueOf("1") == FALSE`. You should check that if its defined and it equals to 0 (or false or no as string, but not the Boolean.valueOf which returns false on everything except ignore-case "true").

Log:
```
20:15:08.039 [INFO] [de.gesellix.docker.client.DockerClientImpl] using docker at 'tcp://127.0.0.1:2376'
20:15:08.074 [DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] dockerTlsVerify=1
20:15:08.078 [INFO] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] assume 'http'
20:15:08.079 [DEBUG] [de.gesellix.docker.client.protocolhandler.DockerURLHandler] selected dockerHost at 'http://127.0.0.1:2376'
```

If you don't have DOCKER_TLS_VERIFY environment variable defined at all, you will correctly get the certPath, etc. defined.

**Comment by gesellix** [comment]
Thanks for reporting the issue! it has been fixed with `de.gesellix:docker-client:2015-03-24T11-45-53`.

**Comment by gesellix** [comment]
in case you used the gradle-docker-plugin: it has been updated, too: http://plugins.gradle.org/plugin/de.gesellix.docker/2015-03-24T14-17-57
